superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('edit/<int:hero_id>', views.edit, name='edit'),
    path('delete/<int:hero_id>', views.delete, name='delete')
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context ={
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero':single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        #save the form contents as a new db object
        #return to index
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    edited_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        edited_hero.name = request.POST.get('name')
        edited_hero.alter_ego = request.POST.get('alter_ego')
        edited_hero.primary = request.POST.get('primary')
        edited_hero.secondary = request.POST.get('secondary')
        edited_hero.catchphrase = request.POST.get('catchphrase')
        edited_hero.save()
    else:
        context = {
            'edited_hero': edited_hero
    }
    return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    delete_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        delete_hero.delete()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        context ={
            'hero':delete_hero
        } 
    return render(request, 'superheroes/delete.html', context)

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Scondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Confirmation</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <p>Are you sure you want to delete "{{hero}}"?</p>
    <form action="{% url 'superheroes:delete' hero.id %} "method="POST">
        {% csrf_token %}
        <input type="submit" name="Confirm">
        <a class="btn btn-sm btn-danger" href="{% url 'superheroes:index' %}">Cancel</a>
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Page</title>
</head>
<body>
    <h1>Details of Heroes</h1>
    <ul>
        <h2>{{single_hero.name}}</h2>
        <li><h3>Alter Ego: {{single_hero.alter_ego}}</h3></li>
        <li><h3>Primary Ability: {{single_hero.primary_ability}}</h3></li>
        <li><h3>Scondary Ability: {{single_hero.secondary_ability}}</h3></li>
        <li><h3>Catchphrase: {{single_hero.catch_phrase}}</h3></li>
    </ul>
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <form action="{%url 'superheroes:edit' edited_hero.id %}" method="post">
        {%csrf_token %} 
        
        Name: <input type="text" name="name" id="name" /><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego" /><br />
        Primary_Ability: <input type="text" name="primary" id="primary" /><br />
        Secondary Ability:<input type="text" name="secondary" id="secondary" /><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase" /><br />
        <input type="submit" value="Confirm">
        </form>
        <a class="btn btn-sm btn-danger" href="{% url 'superheroes:index' %}">Exit</a>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes %}
        <li><h3>{{hero.name}} - <a class="btn btn-sm btn-info" href="{% url 'superheroes:detail' hero.id %}">Click for Details</a>
        <a class="btn btn-sm btn-info" href="{% url 'superheroes:edit' hero.id %}">Update</a> 
        <a class="btn btn-sm btn-danger" href="{% url 'superheroes:delete' hero.id %}">Delete</a></h3></li>
        {% endfor %}
    </ul>
    <a class="btn btn-sm btn-info" href="{% url 'superheroes:create'%}">Add New Hero</a>
</body>
</html>